### ISSUE TITLE
Investigate task not completed warnings

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1268]
This has been discussed before and was brought up again at https://github.com/gulpjs/gulp/issues/1241#issuecomment-141712495

It would be really awesome if gulp 4 could report to users when they forget to call their callback or return a stream/promise/observable/etc.  I am not sure how to achieve this but I would love if someone could investigate this.

Note: gulp 4 doesn't support sync tasks, so the warning would always be valid (unlike gulp 3.x)

**Comment by callumacrae** [comment]
+1, I'd be interested in looking into this.

It would just be a case of checking the function length or checking that the return type is equal to one of [these](https://github.com/phated/async-done#completion-and-error-resolution), right? I guess it could just check for _any_ return value, but that could cause problems with coffeescript.

What about disabling the warning: how would people go about doing that if they know what they're doing and don't want to return anything? `return through.obj()` or something like `this.disableSyncWarning()`?

**Comment by phated** [comment]
You should just be able to use the events emitted by undertaker for start and stop. Maybe warn after a certain amount of time if the stop event isn't emitted?

**Comment by callumacrae** [comment]
But if a task takes one second and it warns after two, it will say that it took 1ms time, and then quit before the warning has time to output. That seems like it would be a fairly common case.

**Comment by phated** [comment]
@callumacrae if a `setTimeout` is set inside the `on('start')` and cleared in the `on('stop')`, the CLI will run until it is cleared or called because you have more async stuff happening (the timeout).  Currently the CLI exits because there are no inherent async things running (we only nextTick each task, so the async has completed before the task finishes).

**Comment by phated** [comment]
@callumacrae @contra and anyone else interested in this, please try out https://github.com/gulpjs/gulp-cli/tree/warn-sync-tasks and give feedback.  It seems to be working in my quick tests but it could probably use a better error message and we might want to make the timeout configurable with a CLI flag.

**Comment by phated** [comment]
Still looking for feedback.  The more I think about this, I think I need to add a `--timeout` flag.

**Comment by contra** [comment]
@phated I think a timeout flag is better aligned with other JS tooling (mocha, for example)

**Comment by phated** [comment]
Added the timeout flag on the linked branch.  Default is 10000 milliseconds.

**Comment by phated** [comment]
I've also merged these changes into the 4.0 branch because I want more people to have eyes on it and it seems a bunch of people are using that branch currently.

**Comment by ckross01** [comment]
@phated the time out flag is really cool and helped with a few items, thanks for including it. Is the intent to have this time out on watch tasks as well?

**Comment by phated** [comment]
@ckross01 yeah, in gulp 4 you should call the callback after registering watches also.  This allows the function to be composed anywhere and doesn't get the pipeline stuck on that sync task.  Just had the same discussion with @terinjokes

**Comment by phated** [comment]
@ckross01 @terinjokes @callumacrae @contra bikeshed time!  how about we set the timeout to 1 minute?  This is just a debugging tool, so hanging for a minute would be annoying but will still result in the error being printed

**Comment by callumacrae** [comment]
I still don't really understand why this needs a timeout. Why not listen to the process `beforeExit` event or an event fired in gulp and throw if nothing was returned / there was no callback?

I think I'm missing something!

**Comment by phated** [comment]
@callumacrae great idea, I have a new implementation over at https://github.com/gulpjs/gulp-cli/tree/new-task-warning-impl and I think this will work __much__ better.  Need some people to test it out

**Comment by callumacrae** [comment]
Here is my gulpfile:

```js
var gulp = require('gulp');

gulp.task('complete', function (done) {
	setTimeout(done, 1000);
});

gulp.task('notcomplete', function (done) {
});

gulp.task('notreturned', function () {
});
```

Output in Gulp 4:

```
❯ ./node_modules/gulp-cli/bin/gulp.js complete
[12:05:28] Using gulpfile ~/tmp/gulp-if-bug/gulpfile.js
[12:05:28] Starting 'complete'...
[12:05:29] Finished 'complete' after 1 s

❯ ./node_modules/gulp-cli/bin/gulp.js notcomplete
[12:05:32] Using gulpfile ~/tmp/gulp-if-bug/gulpfile.js
[12:05:32] Starting 'notcomplete'...
[12:05:32] The following tasks did not complete: notcomplete
[12:05:32] Did you forget to signal async completion?

❯ ./node_modules/gulp-cli/bin/gulp.js notreturned
[12:05:37] Using gulpfile ~/tmp/gulp-if-bug/gulpfile.js
[12:05:37] Starting 'notreturned'...
[12:05:37] The following tasks did not complete: notreturned
[12:05:37] Did you forget to signal async completion?
```

Output when using gulp-cli with Gulp 3:

```
❯ ./node_modules/gulp-cli/bin/gulp.js complete
[12:03:37] Using gulpfile ~/tmp/gulp-if-bug/gulpfile.js
[12:03:37] Starting 'complete'...
[12:03:38] Finished 'complete' after 1 s

❯ ./node_modules/gulp-cli/bin/gulp.js notcomplete
[12:03:43] Using gulpfile ~/tmp/gulp-if-bug/gulpfile.js
[12:03:43] Starting 'notcomplete'...

❯ ./node_modules/gulp-cli/bin/gulp.js notreturned
[12:03:48] Using gulpfile ~/tmp/gulp-if-bug/gulpfile.js
[12:03:48] Starting 'notreturned'...
[12:03:48] Finished 'notreturned' after 60 μs
```

Everything is as expected, except that the notreturned task doesn't seem to complete in the 4.0 branch.

**Comment by phated** [comment]
@callumacrae notreturned isn't supposed to complete in 4.0 as sync tasks were completely removed.  That is actually the reason for adding this warning.  I tested that branch against a similar gulpfile and am hoping to have a few people test it against their actual ones as well as mock ones.  Thanks!

**Comment by callumacrae** [comment]
Ah. I'm still not using Gulp 4—I'll be updating in the next couple weeks, though.

**Comment by phated** [comment]
The new implementation has been merged into 4.0 - Going to close this.  If anyone has feedback, feel free to post it here

**Comment by dacodekid** [comment]
@phated It works well for me. If I'm not mistaken, then the below example code (from gulpjs 4.0) needs to be updated to ```return del(['build']) ```?

```javascript
/* Define our tasks using plain functions */

// Not all tasks need to use streams
// A gulpfile is just another node program and you can use all packages available on npm
function clean(done) {
  // You can use multiple globbing patterns as you would with `gulp.src`
  del(['build'], done);
}
```

**Comment by callumacrae** [comment]
@dacodekid depends whether you're using del 1 or 2. If you're using del 2, return the promise, otherwise use a callback.

https://github.com/sindresorhus/del/releases/tag/v2.0.0

**Comment by dacodekid** [comment]
@callumacrae, no I'm not asking for help :).  The above provided example is actually from gulpjs 4.0 github repo, that emitting ```task not completed``` warning, which I thought might be worth mentioning. My bad for not clearly mentioned my intension :)

**Comment by callumacrae** [comment]
Oh, sorry! Are you talking about the example from this file? And are you definitely using del 2? https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md

**Comment by dacodekid** [comment]
Nope, but this one - https://github.com/gulpjs/gulp/blob/4.0/README.md

The 'clean' task didn't provide a promise/cb return on the example. While I was just copy/pasting the 'clean' function and call via 'default' task, I got the ```task not completed``` warning, that took me to this thread.

**Comment by callumacrae** [comment]
Ah, that's wrong and won't work with the latest version of del. I'll fix it later (or if you could send a PR that would be great!)

**Comment by dacodekid** [comment]
@callumacrae, Thx :). Created a pull request here - https://github.com/gulpjs/gulp/pull/1309.  Hope it fits with Gulp standards or otherwise plz feel free to reject it :).

**Comment by timkelty** [comment]
It seems like `--timeout=0` totally disables this. Is that coincidence or by design? (I first tried `--timeout=-1`), which didn't work.

For me, this feature just doesn't make sense for _every_ task.
I have several tasks that either have prompts that wait for user input (inquirer) or actually involve `ssh`ing to a remote server with an interactive prompt.

Still feel like I should be able to disable this actually in my task options and not just on the cli, though.

**Comment by callumacrae** [comment]
@timkelty Is your version of gulp up to date? If you read through the full issue until where was closed, another approach was chosen. (unless, of course, @phated left the timeout code in as well)

**Comment by timkelty** [comment]
@callumacrae I did read through the issue. The links to the mentioned branches are dead, so I'm not sure I'm supposed to see what the other approach was.

**Comment by phated** [comment]
Listing your version doesn't help anything as none of this is published yet.  You are on an old version of the 4.0 branch.  The code for sync tasks has been switched to @callumacrae's suggestion.  See https://github.com/gulpjs/gulp-cli/blob/4.0/lib/versioned/%5E4.0.0-alpha.1/log/syncTask.js

**Comment by timkelty** [comment]
@phated Right, whoops.
I reinstalled my local gulp, but not my global one (`gulp` command).

Thanks!

**Comment by ghpabs** [comment]
Similar issue here.

**Setup**
```
λ gulp -v
[10:52:08] CLI version 1.0.0
[10:52:08] Local version 4.0.0-alpha.2
```
Windows 7

**Tasks**

```js
var del = require('del');
function clean() {
	return del(['docs', 'coverage', 'build', 'release']);
}

function build() {
	return gulp.series(
		clean
	);
}
```

**Error**
```
λ gulp build
[10:52:22] Using gulpfile C:\project\gulpfile.js
[10:52:22] Starting 'build'...
[10:52:22] The following tasks did not complete: build
[10:52:22] Did you forget to signal async completion?
```
