### ISSUE TITLE
Failed to load external module babel-register

### ISSUE THREAD

**Issue by mrchief** [gulpjs/gulp#1631]
Fresh Node v4.4.3 and npm v3.x install.

```
> gulp -v
[14:55:49] Failed to load external module babel-register
[14:55:49] Requiring external module babel-core/register
[14:55:49] CLI version 3.9.1
[14:55:49] Local version 3.9.1
```

This only happens if the local folder has a `gulpfile.babel.js`. `package.json` has these installed:

```
"babel-core": "^6.7.7",
"babel-preset-es2015": "^6.6.0",
"babel-preset-stage-0": "^6.5.0",
```

`.babelrc`

```
{
  "presets": ["es2015", "stage-0"]
}
```

I even tried `require('babel-core/register');` in `gulpfile.babel.js` but no luck.

Not sure how to fix this.

**Comment by mrchief** [comment]
Downgrading to v3.9.0 (and removing local version) gives this

```
> gulp -v
[14:55:49] Requiring external module babel-core/register
[14:55:49] CLI version 3.9.0
```

**Comment by phated** [comment]
Not an issue, as it states on the next line down, it required `babel-core/register`.  Babel now suggests you use a module called `babel-register` so we try that first with the fallback.  Please read your entire log before creating an issue.

**Comment by mrchief** [comment]
Hmm. So I did `npm i -S babel-register` in order to get rid of the `Failed...` warning. Thanks for pointing in the right direction.

**Comment by amazingSurge** [comment]
I am using ubuntu 14.04. And i am using ```nvm``` managing the nodejs.

Runing ```gulp -v``` getting the error below

```
[20:54:47] Failed to load external module babel/register
[20:54:47] CLI version 3.9.0
[20:54:47] Local version 3.9.1
```
And the issue was solved by the steps below:

```
sudo rm -r /usr/lib/node_modules/
sudo rm /usr/bin/gulp
npm cache clear
npm uninstall gulp-cli -g
npm uninstall gulp -g
npm install gulp-cli -g
```

Hope it will be helped for whom that is using ```nvm```.

**Comment by bORm** [comment]
try install 
```
    "babel-core": "^6.14.0",
    "babel-register": "^6.14.0",
```

**Comment by pgnd** [comment]
For a new project, using
```
	node -v
		v9.2.0
	yarn -v
		1.3.2
```
after
```
	yarn global add gulp-cli
	yarn add --dev https://github.com/gulpjs/gulp.git#master
	yarn add --dev \
	 babel-core \
	 babel-register \
	 babel-preset-env \
	 babel-preset-stage-2 \
	 babel-cli
```
with
```
	cat package.json
	{
	  "name": "test",
	  "version": "1.0.0",
	  "main": "index.js",
	  "license": "MIT",
	  "dependencies": {
	    "jquery": "^3.2.1"
	  },
	  "devDependencies": {
	    "babel-cli": "^6.26.0",
	    "babel-preset-env": "^1.6.1",
	    "babel-preset-stage-2": "^6.24.1",
	    "babel-register": "^6.26.0",
	    "gulp": "https://github.com/gulpjs/gulp.git#master"
	  }
	}

	cat .babelrc
		{
		  "presets": ["es2015", "es2016", "es2017", "stage-2"],
		  "retainLines": true
		}
```
verifying
```
	yarn list | grep babel | grep register | grep "^├─"
		├─ babel-register@6.26.0
```
gulp exec still returns
```
	gulp -v
		[18:29:26] Failed to load external module @babel/register
		[18:29:26] Requiring external module babel-register
		[18:29:26] CLI version 1.4.0
		[18:29:26] Local version 3.9.1
```
@phated given your prior " Please read your entire log before creating an issue.", rather than opening a new issue, what, specifically, in the log above addreses the "Failed to load external module @babel/register" ?  *IS* that 'fail' a real problem, or just to be considered YA-warning?

**Comment by phated** [comment]
It's a warning. Notice the line after?

**Comment by bochen2014** [comment]
1.  we shouldn't have to explicitly install `babel-register` as it's already included in `babel-core` by itself;
```bash
$ npm ls babel-core
simplified-seed@1.0.0 /opt/github/seed-demo
└─┬ babel-core@6.26.0
  └─┬ babel-register@6.26.0
    └── babel-core@6.26.0  deduped
```

2. even I explicitly installed `babel-register` (which I don't see why I need that. I just followed the instructions [above](https://github.com/gulpjs/gulp/issues/1631#issuecomment-216342389) ) I still get the save error. 
I reckon the solution suggested above only work for a particular `babell-core` version

**Comment by DanielRuf** [comment]
We also have this issue and it seems babel loads `@babel/register` even f it is already installed separately cc @zhoo

**Comment by phated** [comment]
Please, please, please understand the projects you are using being spamming closed issues like this.  Babel (yet again) changed the module you require to enable runtime support.  We've updated our internal dependencies to reflect their change and now you see the warning about `@babel/register`.  Your project is still working, it's just attempting to use the "new" babel thing before it uses the old one you are depending on.  Again, please do more research before you spam things like this.
