### ISSUE TITLE
Update docs for v5.0

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#2764]
We need to update the docs (and publish to website) for the v5 release.

**Comment by phated** [comment]
A couple things I noticed during skimming:
* Need to remove the "ordered globs" docs
* Need to update configuration options to vinyl-fs functions

**Comment by Fa-haxiki** [comment]
Oh my gosh, I thought you guys had given up on gulp.

**Comment by yocontra** [comment]
Encoding option added: https://github.com/gulpjs/gulp/blob/master/docs/api/src.md#options

**Comment by phated** [comment]
"Explaining Globs" docs have been updated and a section added with an example for ordered globs using ordered-read-stream: https://github.com/gulpjs/gulp/blob/master/docs/getting-started/6-explaining-globs.md#ordered-globs

**Comment by Sebazzz** [comment]
> Encoding option added: https://github.com/gulpjs/gulp/blob/master/docs/api/src.md#options

Which should be classified as a breaking change, when copying binary files (#2790, #2796).

**Comment by yocontra** [comment]
@Sebazzz It was a breaking change - its why we released a new major release, and its in the changelog as a breaking change for that major release.

**Comment by Sebazzz** [comment]
> @Sebazzz It was a breaking change - its why we released a new major release, and its in the changelog as a breaking change for that major release.

Look at it from an end-user perspective: 

> Default stream encoding to UTF-8

That truly doesn't mean *anything* to an end user.

**Comment by yocontra** [comment]
@Sebazzz We are working on improving the docs - the website not being updated for v5 was an oversight and we are working on it as we speak. The docs in the repo have been updated on gulp and vinyl-fs but I know people look at the website first. More info here: https://github.com/gulpjs/gulp/issues/2790#issuecomment-2062002387

**Comment by stamminator** [comment]
I actually didn't know there was a v5 until I manually checked the version and did a web search for "gulp 5".

**Comment by mrleblanc101** [comment]
Any progress ? It's been nearly 6 months and the docs is still not up to date.
We just debugged an issue where our fonts were not working anymore when copying from `src` to `dest` using `gulp-copy` until we found #2796 which links to #2790.
A migration guide would be nice.

**Comment by phated** [comment]
The markdown docs have been updated and redeployed to the website so I'm going to close this.

As the major v4 release didn't contain a migration guide, we're not considering it required for v5 either. If anyone from the community wants to contribute further docs, like a migration guide, we're happy to review PRs!
