### ISSUE TITLE
Gulp no longer follows symlinks past the first level

### ISSUE THREAD

**Issue by wesleycho** [gulpjs/gulp#792]
I have noticed a regression in Gulp where when using gulp.src, if a directory that is matched is symlinked, it will no longer try to follow nested folders of that directory.  This is due to [this change](https://github.com/wearefractal/vinyl-fs/commit/4d95e2e19f35045ca5ec66d697167078696bfc86) in vinyl-fs.

**Comment by tkalfigo** [comment]
Running into this problem as well. Any updates regarding passing options to src()?

**Comment by heikki** [comment]
Shortcut to node-glob PR -> https://github.com/isaacs/node-glob/pull/148

**Comment by evenfrost** [comment]
Will like this feature as well.

**Comment by phated** [comment]
https://github.com/isaacs/node-glob/pull/148 has been closed by a different commit by @isaacs - is this solved?

**Comment by phated** [comment]
Can someone write a test for this against the [vinyl-fs](https://github.com/wearefractal/vinyl-fs) repo?  I believe it is fixed now that @contra bumped the glob dependency (vinyl-fs 5.0.0)

**Comment by isaacs** [comment]
Note that the glob symlink followin behavior is opt-in, so you need to pass `follow:true` in the options object.

**Comment by contra** [comment]
@isaacs Ah thanks, I need to add that then

**Comment by phated** [comment]
@contra I'm assuming we still want it to be opt-in since it is an edge case.  I've added a note to the 4.0 docs in https://github.com/gulpjs/gulp/commit/725da2a855472b8f99b64b58c181e30c16bfa8a3

**Comment by phazei** [comment]
I specify "follow: true" but still get the same error.  Any way to get this in 3.9?  4's taking years...
